services:
    # URI generator
    vegan.menu.url.generator:
        class: Vegan\MenuBundle\Menu\VeganUrlGenerator
        arguments: [@service_container]

    # Classic menu builder
    vegan.menu.builder:
        class: Vegan\MenuBundle\Menu\MenuBuilder
        arguments: [@service_container, @vegan.menu.url.generator]

    # Database menu builder
    vegan.menu.database.builder:
        class: Vegan\MenuBundle\Menu\DatabaseMenuBuilder
        arguments: [@service_container, @vegan.menu.url.generator]

    # nette/caching component incorporation into Symfony2
    nette.caching:
        class: Vegan\MenuBundle\Component\NetteCaching
        arguments: [%kernel.cache_dir%/nette]
